### ISSUE TITLE
le test requier un crash sur ft_lstiter

### ISSUE THREAD

**Issue by Chr0nos** [alelievr/libft-unit-test#1]
salut,
la fonction ft_lstiter a besoin d un crash dans le test alors que par nature la fonction ne crash pas:

void	ft_lstiter(t_list *lst, void (*f)(t_list *elem))
{
	t_list	*x;

	if (!lst)
		ft_crash();
	x = lst;
	while (x)
	{
		f(x);
		x = x->next;
	}
}

j ai donc du faire une fonction ft_crash pour faire segfault le programe et passer le test, un peu bizard non ?
gerer un simple return NULL ne serais il pas une meilleur solution ?

snicolet

**Comment by alelievr** [comment]
ce test renvoi un KO si tu segfault normalement, c'est pas un fail. J'ai rajouter les KO pour différencier les fail (fonction au comportement anormal) des comportements indéterminés ou aucune référence n'existe pour déterminé le bon comportement.
En gros c'est ta fonction, tu peux choisir de la faire segfault si tu trouve que NULL est un cas d'erreur  (donc ta fonction ne devrais jamais en recevoir) ou tu peux return NULL si tu considère que si tu considère que NULL est une liste sans éléments.
