### ISSUE TITLE
Bug quand on lance le check si un fichier est ouvert avec vim

### ISSUE THREAD

**Issue by Gary2222** [alelievr/libft-unit-test#10]
Bonjour, si on lance le checking, la partie "A" bug si un fichier est ouvert ca dit que ca n'a pas pu compiler, si on ferme vim et le fichier ca ne bug plus.
J'en conclu que le fichier .swp doit avoir un impact. ca vient ptet de mon Makefile mais je vous invite a tester de votre coté au cas ou :)

**Comment by alelievr** [comment]
Bonjour, aucun problème à signaler de mon coter si vim est ouvert, je pense pense que le problème viens de ton Makefile. Vérifie si tu n'utilise pas d'* dans ton makefile, c'est peut-etre la source de ton problème.
