### ISSUE TITLE
MAP_ANONYMOUS n'est pas déclaré

### ISSUE THREAD

**Issue by MiloParigi** [alelievr/libft-unit-test#13]
Problème quand je fait un make avec un git clone tout frais :

> src/main.c:266:72: error: use of undeclared identifier 'MAP_ANONYMOUS'
>         if ((g_shared_mem = mmap(NULL, sizeof(t_map), PROT_READ | PROT_WRITE, MAP_ANONYMOUS | MAP_SHARED, -1, 0)) == MAP_FAILED)

**Comment by alelievr** [comment]
Salut,
es-tu sous linux ?

**Comment by MiloParigi** [comment]
Non, je suis sur un mac !

**Comment by alelievr** [comment]
C'est bizzare, c'est la premiere fois que je vois ce bug sous mac.
Essaye de remplacer `MAP_ANONYMOUS` par `MAP_ANON`.
