### ISSUE TITLE
relocation R_X86_64_32 against `.rodata'

### ISSUE THREAD

**Issue by Extazya** [alelievr/libft-unit-test#20]
Hello,

I have try to compile this on my Linux : 

➜  libft-unit-test git:(master) ✗ uname -a
Linux reya 4.4.0-51-generic #72-Ubuntu SMP Thu Nov 24 18:29:54 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

and i have this error : 
➤  clang -shared -fPIC assets/tmp/ft_atoi.o assets/tmp/ft_bubble_sort_char.o assets/tmp/ft_bubble_sort_char_reverse.o assets/tmp/get_next_line.o [...] -o libft.so 

/usr/bin/ld: assets/tmp/ft_mini_tabi.o: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC

assets/tmp/ft_mini_tabi.o: error adding symbols: Bad value
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:145: recipe for target 'libft.so' failed
make: *** [libft.so] Error 1

but in your Makefile : 

CFLAGS          =       -Werror -Wall -Wextra# -ggdb# -fsanitize=address
CSOFLAGS        =       -shared -fPIC
CSOFLAGS2       =
CC                      =       clang

any idea what happen ?

**Comment by alelievr** [comment]
Hello, you are on the master branch of the project, for linux there is a branch called 'linux', please switch and tell me if it work (more info in the readme).

**Comment by alelievr** [comment]
OK nice ! Good luck for optimizing your libft ! :)
