### ISSUE TITLE
ft_memmove: check malloc

### ISSUE THREAD

**Issue by Chr0nos** [alelievr/libft-unit-test#3]
le test authorise malloc/free dans ft_memmove alors que la fonction ne devrais pas en contenir, je me demandais si cela etait voulu ou s'il s'agissait d'un oubli :)

**Comment by alelievr** [comment]
ouais mais la manière de faire cette fonction n'est pas vraiment explicite, meme si il est vrais qu'elle ne devrais pas contenir de malloc, ce n'est pas une fonction interdite dans la premiere partie.
Pense tu vraiment qu'il soit nécessaire de tester si il n'y a pas de malloc en sachant que la fonction peut très bien fonctionner avec meme si c'est beaucoup moins opti.

**Comment by Chr0nos** [comment]
et bien je pense que oui car si on suppose que l on est sur un systeme avec 4go de ram, on veu memmove 3go : ca doit passer avec une memmove normale, du coup ce n est plus vraiment un probleme d'opti mais vraiment de logique, qu en pense tu ?

**Comment by alelievr** [comment]
Ouais je vais ajouter un test pour voir si il y a un malloc dans memmove, de toute facons coder un memmove avec malloc est une mauvaise idée
