### ISSUE TITLE
ft_strnstr missing test?

### ISSUE THREAD

**Issue by Gabriel-Em** [alelievr/libft-unit-test#41]
there are some implementations of strnstr that pass all tests even though there are tests that they fail.
for instance i've found the following test to fail in some implementation but not to be treated in the unit-tests

char *big = "abcdef";
char *little = "abcdefghijklmnop"

ft_strnstr(big, little, strlen(big));

Specifically a test case in which both strings are equal up to a point but little is actually greater in length than big, though strnstr is being asked to search only the first strlen(big) characters. In this case little is not found in big, but there are some wrong implementations of ft_strncat which will return a pointer to 'a', which is wrong. The thing is that your unit tests don't seem to catch that mistake.

This is an example of an implementation of ft_strnstr that passed the unit tests in this library but doesn't actually work like the real strnstr.
```
#include "libft.h"

char	*ft_strnstr(const char *big, const char *little, size_t len)
{
	size_t len_little;
	size_t i;

	len_little = ft_strlen(little);
	if (len_little == '\0')
		return ((char*)big);
	if (len_little > len)
		len_little = len;
	i = 0;
	while (i <= len - len_little)
	{
		if (big[i] == little[0])
			if (!ft_strncmp(big + i, little, len_little))
				return ((char*)(big + i));
		i++;
	}
	return (NULL);
}
```

**Comment by alelievr** [comment]
Hello, 

Yup, you're right, this test was missing for the strnstr function.
I've added this test in the latest commit: 994c920f35c13b01aac5726d1ebd65d83153e52c, thanks for you contribution :)
