### ISSUE TITLE
atof test

### ISSUE THREAD

**Issue by Karocyt** [alelievr/libft-unit-test#43]
Tu compare le résultat à l'original, mais par définition, le NaN n'est égal à rien, même pas à lui-même, donc le test semble impossible par conception.

(nan == nan) -> false
isnan(nan) -> true

Des bisous et merci pour tout !

**Comment by alelievr** [comment]
Salut, merci pour cette issue :)

J'ai fix le test dans le commit c09f975.

**Comment by alelievr** [comment]
Je viens de fix le bug du test sur strsplit, pour le lstmap tu pourrais expliquer un peu plus le comportement de ta fonction que j'ajuste le test ?
