### ISSUE TITLE
ft_memcmp has four tests which are expecting wrong results.

### ISSUE THREAD

**Issue by z10n-w3n** [alelievr/libft-unit-test#44]
ft_memcmp:     [OK] [OK] [OK] [FAILED] [FAILED] [FAILED] [FAILED] [OK] [OK] [OK] 
[fail]: your memcmp does not work with basic input
[fail]: your memcmp does not cast the memory in unsigned char
[fail]: your memcmp stop at 
[fail]: your memcmp does not work with basic input

According to 'man memcmp', those four test above should not expect -1 or 1 but difference between the first two differing bytes.

```
RETURN VALUES
     The memcmp() function returns zero if the two strings are identical, otherwise returns the difference between the first
     two differing bytes (treated as unsigned char values, so that `\200' is greater than `\0', for example).  Zero-length
     strings are always identical.  This behavior is not required by C and portable code should only depend on the sign of the
     returned value.
```

**Comment by z10n-w3n** [comment]
This bug is bugging everyone in the 42 silicon valley. Please fix it.

**Comment by alelievr** [comment]
Hello,

I'm checking the result of ft_memcmp against the system's implementation, can you tell me what version of OSX you are using ?
It may be related to their last update, it will not be the first time that apple doesn't follow the man.

**Comment by z10n-w3n** [comment]
It is HS 10.13.3
I tested on a couple of iMacs. some pass some fail.
But on the iMacs that failed, I wrote a test main calls the system memcmp. It returned the distance other than 1 or -1. Still couldn't figure out why.

**Comment by z10n-w3n** [comment]
By the way. Could you teach me how to make ft_putchar work with unicode? Did some googling and asked around but couldn't find out.

**Comment by alelievr** [comment]
I fixed the bug by adding the GNU implementation of memcmp so it follow the man and for the putchar unicode, it not mandatory for the libft but if you want to implement it you can have a look to the [wikipedia UTF-8](https://en.m.wikipedia.org/wiki/UTF-8#Description) page, it will explain you how to decode UTF-8 in bytes to print them in the terminal.
