### ISSUE TITLE
LSOpenURLsWithRole() failed with error -600

### ISSUE THREAD

**Issue by tspies** [alelievr/libft-unit-test#45]
Cannot open error log after tests have run.

**Comment by alelievr** [comment]
Hello, can you provide more informations about your problem ? like how are you opening the log file and the permissions on this file.

Thanks.

**Comment by tspies** [comment]
Good Day.

Unfortunately I have since we last spoke I have lost the file, so I cannot
tell you what my permissions where, however I think the error must have
stemmed from the generic text editor on my computer as that kept crashing.

I have reinstalled 42 File Checker and have had no problems since.
Thank you for your speedy response.

Kind Regards
Tristyn Spies

**Comment by alelievr** [comment]
Hello, It's okay, i'll close the issue and if the problem comes up again let me know :)
