### ISSUE TITLE
strsplit

### ISSUE THREAD

**Issue by hugodu69** [alelievr/libft-unit-test#48]
I believe there is an issue on the strsplit test. this is the report of the result.log file :

> ft_strsplit:   [FAILED] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] {protected}
> [fail]: your strsplit does not work with basic input
> Test code:
>         char *string = "      split       this for   me  !       ";
>         char **expected = ((char*[6]){"split", "this", "for", "me", "!", ((void *)0)});
>         char **result = ft_strsplit(string, ' ');
> 
> 
>         split_cmp_array(expected, result);
> 
> 
> Diffs:
>     strsplit: |p^Bàà°^?|
> ft_strsplit: |split|

it seems that my ft_strsplit works well by printing out the result "split" but your output looks weird "p^Bàà°^?", or am i wrong ?

EDIT : on my computer with linux mint it did this weird result, but on Mac everything's ok

**Comment by alelievr** [comment]
Hi, as said in #53, the result log for strsplit was reversed so it was your function that returned "p^Bàà°^?", it's fixed in c67374a.
