### ISSUE TITLE
test missing on ft_strrchr.c

### ISSUE THREAD

**Issue by hugodu69** [alelievr/libft-unit-test#49]
my ft_strrchr succeed all your tests but it's actually wrong, it doesn't check the str[0] character, so I think you'r missing a test, something for this situation : ft_strrchr("abbbbbbbb", 'a'); which should render "abbbbbbbb" (and not NULL like mine do...)

**Comment by alelievr** [comment]
Hi, this was fixed in 3b2d111, thanks for your contribution !
