### ISSUE TITLE
Test strcmp && strncmp

### ISSUE THREAD

**Issue by kkuette** [alelievr/libft-unit-test#5]
Les tests strcmp && strncmp ne sont pas complet;

Il manque de verifier si s1 != '\0' || s2[i] != '\0';
A la moulinette mes deux fonctions ont fail a cause de cette verification, il faudrait ajouter les tests suivants : 
              -strcmp("aaa", "");
              -strncmp("aaa", "");
              -strcmp("", "aaa");
              -strncmp("", "aaa");

cordialement tdenion;

**Comment by alelievr** [comment]
c'est bon je les aient ajoutés, merci pour l'info !
