### ISSUE TITLE
outputs inverses dans le result.log pour ft_strsplit

### ISSUE THREAD

**Issue by KeroK127** [alelievr/libft-unit-test#53]
ft_strsplit:   [OK] [OK] [OK] [FAILED] [OK] [OK] [FAILED] [CRASH] [FAILED] {not protected}
	[fail]: your strsplit does not work with one word
	Test code:
	char *s = "olol                     ";
	char **result = ft_strsplit(s, ' ');

	split_cmp_array(expected, result);

	Diffs:
	strsplit: ||
 	ft_strsplit: |olol|

L'erreur est vraiment mineure. Après test, mon programme est celui qui a sorti '||' et strsplit a sorti '|olol|'.
Autrement, dans la diff les outputs sont inversés. On aurait du avoir : 

	Diffs:
	strsplit: |olol|
	ft_strsplit: ||

**Comment by alelievr** [comment]
Salut, en effet la diff est inversée sur le split, j'ai fix ca dans c67374a, merci pour la contrib.
