### ISSUE TITLE
Memcpy no crash

### ISSUE THREAD

**Issue by CyberDuck79** [alelievr/libft-unit-test#59]
Hello, I just run the libft-unit-test and the test say me that there is an error in ft_memcpy because is doesn't crash when both pointer are null and size at 0.
I was first thinking that was weird that a function who do not crash can be seen as an error but then I think that surely the original memcpy behave that manner... but no.
Literaly try the two functions in one main with the parameters you set in the test (I check the source) but the original function do not crash.

**Comment by CyberDuck79** [comment]
OK seem the IRAISE instead of RAISE error is still there

**Comment by CyberDuck79** [comment]
But my code was still false (not dst == src check) so thanks you for this update ;)

**Comment by alelievr** [comment]
Yep the IRAISE/RAISE issue was still here for the memcpy, it should be fixed now :)
