### ISSUE TITLE
'\0' dans ft_strcpy

### ISSUE THREAD

**Issue by llellouc** [alelievr/libft-unit-test#6]
Salut,
Il n'y a pas de tests permettant de vérifier qu'il y avait bien un '\0' à la fin de notre chaine dst.
A+

**Comment by Morovaille** [comment]
As-tu un exemple concret s'il te plaît ? Quel test ?
Parce que j'ai l'impression que c'est déjà le cas : la chaîne dst est initialisée avec des caractères non-nuls, et après la copie on fait un strcmp sur src et dst. Donc si la chaîne n'est pas terminée par '\0', le strcmp va renvoyer une valeur différente de zero.

**Comment by llellouc** [comment]
J'ai push ma fonction ft_strcpy et faute d'intention, j'ai pas mis le '\0' : 
`char	*ft_strcpy(char *dst, const char *src)
{
	int i;

	i = 0;
	while (src[i] != '\0')
	{
		dst[i] = src[i];
		i++;
	}
	return (dst);
}
`
Et le test me disait que toutes mes fonctions étaient bonnes. Et évidement, la moulinette m'a dit fail sur mon ft_strcpy

**Comment by alelievr** [comment]
j'ai rajouter un test pour le \0 dans strcpy mais c'est quand meme bizzare que le test basique ne l'ai pas détecté
