### ISSUE TITLE
function prototype changed

### ISSUE THREAD

**Issue by troplolBE** [alelievr/libft-unit-test#66]
https://github.com/alelievr/libft-unit-test/blob/3704675f9b90bab55a58aa78885c63b5c1fe02ab/src/test_functions.c#L7565

The prototype of function ft_lstdelone changed from `t_list **, void (*)(void *, size_t)` to `t_list *, void (*)(void *, size_t)`

**Comment by alelievr** [comment]
Hey, this should be fixed with the #64 PR (merged in master)
