### ISSUE TITLE
Update "ft_lstmap" to take extra function param "del"

### ISSUE THREAD

**Issue by AlaaZorkane** [alelievr/libft-unit-test#68]
![image](https://user-images.githubusercontent.com/2952507/67161327-4e1dff00-f351-11e9-969d-f9967cc89230.png)

**Comment by ggjulio** [comment]
I made a PR updating the proto, but can't find a way to make it crash when using the old proto.

**Comment by ggjulio** [comment]
Also, I did not find an easy way to test a malloc fail.

**Comment by alelievr** [comment]
merged in master
