### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by mueslimak3r** [alelievr/libft-unit-test#70]
make: Entering directory '/home/john/github/42FileChecker/libft-unit-test'
\033[38;5;46m make re -C /home/john/github/terence_libft \033[31m
make[1]: Entering directory '/home/john/github/terence_libft'
rm -f ft*.o
rm -f libft.a
gcc -c -Wall -Wextra -Werror ft*.c
ar rc libft.a ft*.o
ranlib libft.a
make[1]: Leaving directory '/home/john/github/terence_libft'
\033[38;5;196;m[  Cleaning #0  ]\033[0m
\033[38;5;196mM-bM-^-$ \033[38;5;9m rm -f obj/src/main.o obj/src/test_functions.o obj/src/display_test_result.o obj/src/signal.o obj/src/sandbox.o obj/src/bench_functions.o obj/src/additional_functions.o obj/hardcore-mode/hardcore-main.o obj/hardcore-mode/error.o obj/hardcore-mode/ncurses-display.o obj/hardcore-mode/test-init.o obj/hardcore-mode/test-utils.o obj/hardcore-mode/test-strcpy.o obj/hardcore-mode/test-strcmp.o obj/hardcore-mode/test-strncmp.o obj/hardcore-mode/test-memset.o obj/hardcore-mode/test-memcpy.o obj/hardcore-mode/test-memccpy.o obj/hardcore-mode/test-memmove.o obj/hardcore-mode/test-memchr.o obj/hardcore-mode/test-memcmp.o obj/hardcore-mode/test-strlen.o obj/hardcore-mode/test-strncpy.o obj/hardcore-mode/test-strcat.o obj/hardcore-mode/test-strncat.o obj/hardcore-mode/test-strchr.o obj/hardcore-mode/test-strrchr.o obj/hardcore-mode/test-strstr.o \033[31m
\033[38;5;196mM-bM-^-$ \033[38;5;9m rm -f libft.so assets/libft.a assetslibtests assets/malloc.dylib \033[31m
\033[38;5;196mM-bM-^-$ \033[38;5;9m rm -f run_test \033[31m
\033[38;5;46m make -j 3 -C /home/john/github/terence_libft \033[31m
make[1]: Entering directory '/home/john/github/terence_libft'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/john/github/terence_libft'
\033[38;5;46m make bonus -j 3 -C /home/john/github/terence_libft \033[31m
make[1]: Entering directory '/home/john/github/terence_libft'
make[1]: *** No rule to make target 'bonus'.  Stop.
make[1]: Leaving directory '/home/john/github/terence_libft'
make: *** [Makefile:180: assets/libft.a] Error 2
make: Leaving directory '/home/john/github/42FileChecker/libft-unit-test'

**Comment by alelievr** [comment]
Fixed here: 15cebb01b5618aba81c7eb07bc655263fa6508e3
