### ISSUE TITLE
Too many arguments provided to function-like macro invocation

### ISSUE THREAD

**Issue by rchioreanu** [alelievr/libft-unit-test#8]
Hi,

I am trying to use the test but I get stuck at this error when it tries to " clang -02 -funroll-loops -Wall -Wextra -Werror -I./include -o obj/main.o -c src/main.c" I am running Ubuntu 16.04 LTS.

Thanks

**Comment by alelievr** [comment]
Hi,

Are you on the linux branch of the libft-unit-test ? and can i get more info about your problem ?

**Comment by rchioreanu** [comment]
Hi,

I didn't notice the linux branch :)

Thanks
