### ISSUE TITLE
[crash]: ft_putnbr_fd.c

### ISSUE THREAD

**Issue by mrtintin13130** [alelievr/libft-unit-test#86]
Thank you, for this program, really usefull !
But it says for my putnbr_fd :
"[crash]: your putnbr_fd allocate memory, wtf ???"
The point is that i'm not allocating memory on any function used with putnbr_fd and not even with putnbr_fd.

**Comment by alelievr** [comment]
Hello, are you sure you're not using a `ft_itoa` in your function?
I'm asking because I never heard about an issue with the malloc checks.
