### ISSUE TITLE
OMG you crashed my program

### ISSUE THREAD

**Issue by jzck** [alelievr/libft-unit-test#9]
Salut, j'ai un message d'erreur qui me demande d'etre reporté !

`                      First part
.-"-.     .-"-.     .-"-.     .-"-.     .-"-.     .-"-.
     "-.-"     "-.-"     "-.-"     "-.-"     "-.-"    
ft_memset:     [OK] [OK] [OK] [OK] [OK] [OK] [OK] 
ft_bzero:      [OK] [OK] [OK] [OK] 
ft_memcpy:     [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] 
ft_memccpy:    [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] 
ft_memmove:    [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] 
ft_memchr:     [OK] [OK] [OK] [OK] [OK] [OK] [OK] 
ft_memcmp:     [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] 
ft_strlen:     [OK] [OK] [NO CRASH] [OK] [OK] [OK] [OK] run_test(61676,0x7fff7dc57000) malloc: *** error for object 0x1074c963e: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

[no crash]: your strlen does not segv when null is sended
[SIGABRT]: abort program (formerly SIGIOT)
OMG you crashed my program, please report this bug to @alelievr !
thanks`

ca a l'air d'etre le 8eme test de ft_strlen (SANDBOX_SPEED) qui crash, je comprends pas pourquoi

**Comment by alelievr** [comment]
Salut, je ne pense pas que le problème soit sur le strlen mais plustot sur le strdup qui est tester juste après (l'affichage a un peut de retard).
Peut-tu m'envoyer ton strdup si tu l'as fais ?

**Comment by jzck** [comment]
C'est bon du coup, j'avais pas protégé le malloc de ft_strdup... merci!

**Comment by alelievr** [comment]
Mon test est est sensé le gérer ce cas et pas crash comme il l'as fais, ca me semble quand meme un peut bizar, si t'as un peut de temps je peux passer pour essayer de trouver ce que c'est ?

**Comment by jzck** [comment]
`char    *ft_strdup(const char *s1)
{
        char    *dup;
        int             size;
        int             i;

        i = 0;
        size = ft_strlen(s1);
        dup = (char*)malloc(sizeof(*dup) * (size + 1));
        if (!dup)
                return (NULL);
        while (s1[i])
        {
                dup[i] = s1[i];
                i++;
        }
        dup[i] = '\0';
        return (dup);
}`

Voila code qui marche, l'erreur survient sans les 2 lignes de protection du malloc.

**Comment by alelievr** [comment]
de mon coté ca marche sans problème ca doit etre une combinaison de facteurs ...
