### ISSUE TITLE
ctype tests with undefined behavior

### ISSUE THREAD

**Issue by fletcher97** [alelievr/libft-unit-test#92]
According to C standard section 7.4 paragraph 1:

> In all cases the argument is an int, the value of which shall be representable as an unsigned char or shall equal the value of the macro EOF . If the argument has any other value, the behavior is undefined.

In your tests you are testing values ranging from -1 to 530 in the is... functions and -100 to 530 in the to... functions. Not sure how this handles in OS X but I'm using linux and it's giving me "FAILED" in some functions like isalnum. The function is literally `return (ft_isalpha(c) || ft_isdigit(c));` and they both isalpha and isdigit passed. The undefined behavior is considering 262 as an alnum according to the c implementation when the input itself is wrong.

The test should only go up to 255 and include EOF to avoid comparing undefined behavior as it gives no meaningful information and may fails the program when there is nothing wrong with it.

Exemple (the 262 was the value that failed isalnum and `r:1` is the return of the standard isalnum converted to 0 or 1 so it's returning true):

![image](https://user-images.githubusercontent.com/9729490/102380362-bbfaa080-3fbf-11eb-804b-844bf9d20e05.png)

**Comment by brhaka** [comment]
@fletcher97 I'm having the same issue. I hope this gets attention soon
